//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCCURD.Dbcontent
{
    using System;
    using System.Collections.Generic;
    
    public partial class empdetail
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Course { get; set; }
        public string gender { get; set; }
        public string Mobile { get; set; }
        public string email { get; set; }
    }
}
